version: "3.5"

services: 
    app:
        build:
            context: ./gs-reactive-rest-service/complete
        ports: 
            - 80:8080
        volumes:
            - ./gs-reactive-rest-service/complete:/app
